definitions:
  models.User:
    properties:
      account_id:
        example: 1
        type: integer
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      name:
        example: red wine No14
        type: string
      updated_at:
        type: string
    type: object
  response.Response:
    properties:
      code: {}
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /cloud/add_user:
    post:
      consumes:
      - application/json
      description: 添加用户
      parameters:
      - description: id
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 默认的 user 接口
      tags:
      - User
  /ping:
    get:
      consumes:
      - application/json
      description: 返回 server 相关信息，可以用于健康检查
      parameters:
      - description: you can set custom trace id in header
        in: header
        name: trace_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 默认的 Ping 接口
      tags:
      - ping
swagger: "2.0"
