definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.User:
    properties:
      account:
        example: q656141982
        type: string
      avatar:
        type: string
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        example: 77677@qq.com
        type: string
      id:
        type: integer
      last_login:
        example: "2021-10-11 20:11:22"
        type: string
      name:
        example: 晓晓
        type: string
      password:
        example: w11111
        type: string
      phone:
        example: "13730884444"
        type: string
      status:
        type: string
      updated_at:
        type: string
    required:
    - account
    - name
    - password
    - phone
    type: object
  response.Response:
    properties:
      code: {}
      data: {}
      msg:
        type: string
    type: object
  routes.login:
    properties:
      account:
        type: string
      captcha:
        description: Captcha  string `form:"captcha" json:"captcha" binding:"required"`
        type: string
      password:
        type: string
    required:
    - account
    - password
    type: object
info:
  contact: {}
paths:
  /cloud/add_user:
    post:
      consumes:
      - application/json
      description: 添加用户
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 默认的 user 接口
      tags:
      - User
  /cloud/captcha:
    get:
      consumes:
      - application/json
      description: 用户登录接口
      parameters:
      - description: data
        in: path
        name: v
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 默认的 captcha 接口
      tags:
      - Captcha
  /cloud/login:
    post:
      consumes:
      - application/json
      description: 用户登录接口
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/routes.login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 默认的 user 接口
      tags:
      - Login
  /ping:
    get:
      consumes:
      - application/json
      description: 返回 server 相关信息，可以用于健康检查
      parameters:
      - description: you can set custom trace id in header
        in: header
        name: trace_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 默认的 Ping 接口
      tags:
      - ping
swagger: "2.0"
